

ALTER TABLE [dbo].[DONOR] ADD 
    [SOCIAL_SECURITY_NUMBER] NVARCHAR (12)   NOT NULL,
    [BLOOD_GROUP_RH]         NVARCHAR (12)  NOT NULL,
    [BLOOD_GROUP_AB0]        NVARCHAR (12)  NOT NULL
;

ALTER TABLE [dbo].[RECIPIENT] ADD 
    [SOCIAL_SECURITY_NUMBER] NVARCHAR (12)   NOT NULL,
    [BLOOD_GROUP_RH]         NVARCHAR (12)  NOT NULL,
    [BLOOD_GROUP_AB0]        NVARCHAR (12)  NOT NULL
;
