

CREATE TABLE [dbo].[RECIPIENT] (
    [PK]        UNIQUEIDENTIFIER DEFAULT (newid()) NOT NULL,
    [FIRST_NAME]      NVARCHAR (100)   NOT NULL,
    [LAST_NAME]      NVARCHAR (100)   NOT NULL,
    PRIMARY KEY CLUSTERED ([PK] ASC)
);

ALTER TABLE [dbo].[DONOR] DROP COLUMN
    [NAME],
    [SHOESIZE]
;

ALTER TABLE [dbo].[DONOR] ADD 
    [FIRST_NAME]      NVARCHAR (100)   NOT NULL,
    [LAST_NAME]      NVARCHAR (100)   NOT NULL
;
